language: node_js
sudo: false
node_js:
  - "4"
  - "5"
  - "6"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g protractor
  - npm start > /dev/null &
  - npm run update-webdriver
  - sleep 1 # give server time to start
  - npm install -g karma-cli

script:
  - karma start test/karma.conf.js --no-auto-watch --single-run --reporters=dots --browsers=Firefox
  - node node_modules\mocha\bin\_mocha test --recursive
  
